name: mini_hackathon_three
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  get_it: ^7.7.0
  freezed: ^2.5.2
  logging: ^1.2.0
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  flutter_dotenv: ^5.1.0
  json_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true
  assets:
    - .env
